"""Load and validate a recipe manifest.

The manifest is the deterministic half of the design, so this module's job is to be
strict about it. Every check here corresponds to a way a manifest can be quietly wrong
and produce a build that installs cleanly and misbehaves later.

Schema: docs/MANIFEST_SCHEMA.md
"""
from __future__ import annotations

import pathlib
from dataclasses import dataclass, field
from typing import Any

import yaml

VIRTUALISED_ROOTS = {"data", "fomod"}

#: postInstall operations the installer implements. The schema decides what a manifest may
#: say; instance.py decides what it does. Adding one here without adding it there is the
#: defect this list exists to stop shipping twice.
POST_INSTALL_OPS = {"delete"}


class ManifestError(Exception):
    """A manifest problem the user must fix. Never auto-corrected."""


@dataclass
class Entry:
    """One mod or tool. `raw` keeps everything so nothing is lost round-tripping."""

    id: str
    name: str
    raw: dict[str, Any]

    @property
    def source(self) -> dict:
        return self.raw.get("source") or {}

    @property
    def install(self) -> dict:
        return self.raw.get("install") or {}

    @property
    def file(self) -> dict:
        return self.raw.get("file") or {}

    @property
    def root(self) -> str:
        return self.install.get("root", "data")

    @property
    def virtualised(self) -> bool:
        """True if MO2 owns it. False means it lands in the game dir, outside usvfs."""
        return self.root in VIRTUALISED_ROOTS

    @property
    def enabled(self) -> bool:
        return bool(self.raw.get("enabled", True))

    @property
    def tier(self) -> str:
        return self.raw.get("tier", "")

    @property
    def pinned(self) -> bool:
        return bool(self.file.get("sha256"))


@dataclass
class Manifest:
    path: pathlib.Path
    game: dict
    tools: list[Entry] = field(default_factory=list)
    mods: list[Entry] = field(default_factory=list)
    order: dict = field(default_factory=dict)

    # --- the ordering rule, in exactly one place -------------------------------
    def modlist_lines(self, harness: str | None = None) -> list[str]:
        """Emit modlist.txt content.

        MEASURED, NOT ASSUMED: modlist.txt is winner-first, so `order.install` (also
        winner-first) is written out VERBATIM. There is no reversal. An earlier version
        of the spec said to reverse it, which would have handed every conflict to the
        loser. See core/tests/test-conflict-order.ps1 and docs/MO2_PORTABLE.md §4.
        """
        by_id = {e.id: e for e in self.mods}
        lines = ["# This file was automatically generated by Mod Organizer."]
        if harness:
            # The harness is a test instrument, not part of the recipe. It goes at the
            # top so it can never be a conflict loser and skew what is being measured.
            lines.append(f"+{harness}")
        for slug in self.order.get("install", []):
            e = by_id[slug]
            lines.append(("+" if e.enabled else "-") + e.name)
        return lines

    def installable(self) -> list[Entry]:
        """Mods we actually install, in conflict order. Candidates are never installed."""
        by_id = {e.id: e for e in self.mods}
        out = [by_id[s] for s in self.order.get("install", [])]
        out += [e for e in self.mods if e.tier != "candidate" and not e.virtualised]
        return out

    def unresolved(self) -> list[Entry]:
        return [e for e in (self.tools + self.mods) if e.tier != "candidate" and not e.pinned]


def load(path: str | pathlib.Path, *, strict: bool = True) -> Manifest:
    p = pathlib.Path(path)
    doc = yaml.safe_load(p.read_text(encoding="utf-8"))
    if not isinstance(doc, dict):
        raise ManifestError(f"{p}: not a mapping")
    if doc.get("schema") != 1:
        raise ManifestError(f"{p}: unsupported schema {doc.get('schema')!r}")

    m = Manifest(
        path=p,
        game=doc["game"],
        tools=[Entry(e["id"], e.get("name", e["id"]), e) for e in doc.get("tools", [])],
        mods=[Entry(e["id"], e.get("name", e["id"]), e) for e in doc.get("mods", [])],
        order=doc.get("order") or {},
    )
    problems = validate(m)
    if problems and strict:
        raise ManifestError(f"{p}:\n  " + "\n  ".join(problems))
    return m


def validate(m: Manifest) -> list[str]:
    """Return problems. Empty list means the manifest is internally consistent.

    Consistency is not correctness: it says nothing about whether the pins point at the
    right files, only that the document does not contradict itself.
    """
    out: list[str] = []

    seen_id, seen_name = set(), set()
    for e in m.tools + m.mods:
        if e.id in seen_id:
            out.append(f"duplicate id: {e.id}")
        seen_id.add(e.id)

    for e in m.mods:
        # A mod's directory name is its identity on disk; two mods sharing one would
        # silently merge into a single directory.
        if e.name in seen_name:
            out.append(f"duplicate mod name (would collide in mods/): {e.name!r}")
        seen_name.add(e.name)
        if not str(e.raw.get("why", "")).strip():
            out.append(f"{e.id}: missing `why` (required — see MANIFEST_SCHEMA.md)")

    order = m.order.get("install", [])
    if len(order) != len(set(order)):
        out.append("order.install contains duplicates")
    for slug in order:
        if slug not in seen_id:
            out.append(f"order.install references unknown id: {slug}")

    for e in m.mods:
        if e.tier == "candidate":
            continue
        if e.virtualised and e.id not in order:
            out.append(
                f"{e.id}: virtualised (root={e.root}) but missing from order.install — "
                "conflict priority would be undefined"
            )
        if not e.virtualised and e.id in order:
            out.append(
                f"{e.id}: root={e.root} lives outside usvfs and must NOT be in order.install"
            )

    for e in m.mods + m.tools:
        root = e.root
        if root not in VIRTUALISED_ROOTS | {"game", "instance"}:
            out.append(f"{e.id}: unknown install.root {root!r}")
        if root == "fomod" and "fomodChoices" not in e.install:
            out.append(f"{e.id}: root=fomod requires install.fomodChoices (may be null)")
        if root == "game" and not e.raw.get("uninstall"):
            # These are the only files we leave outside the instance, so an uninstall
            # note is the difference between reversible and permanent.
            out.append(f"{e.id}: root=game requires an `uninstall` note")
        out += _post_install_problems(e, root)

    return out


def _post_install_problems(e: Entry, root: str) -> list[str]:
    """Check `postInstall`, the key that spent a fortnight declared and unimplemented.

    full-dialog-vr has carried `postInstall: - delete: interface/MultiActivateMenu.swf`
    since 2026-08-16 and nothing read the key, so the step was done by hand and undone by
    the next install. A key that parses and does nothing is worse than one that fails: it
    reads as a fix already in place. Hence a schema check here and an implementation in
    instance.py, in the same commit.
    """
    steps = e.raw.get("postInstall")
    if steps is None:
        return []
    if not isinstance(steps, list) or not steps:
        return [f"{e.id}: postInstall must be a non-empty list of steps"]

    out: list[str] = []
    if root in ("game", "instance"):
        # root=game copies into the user's game directory. A delete there removes a file
        # this recipe never put there — outside the instance, outside the backup
        # _install_into_game takes, and outside anything `uninstall` can restore.
        # root=instance is skipped by cmd_install entirely, so a step declared there would
        # be the same silent no-op this key was added to stop being.
        out.append(f"{e.id}: postInstall is not supported for root={root} — root=game "
                   "would delete from the game directory, outside the instance and any "
                   "backup, and root=instance entries are skipped by `install` entirely")
    for step in steps:
        if not isinstance(step, dict) or len(step) != 1:
            out.append(f"{e.id}: each postInstall step is a single `op: path` mapping, "
                       f"got {step!r}")
            continue
        (op, rel), = step.items()
        if op not in POST_INSTALL_OPS:
            out.append(f"{e.id}: unknown postInstall operation {op!r} "
                       f"(implemented: {', '.join(sorted(POST_INSTALL_OPS))})")
            continue
        s = str(rel or "").strip().replace("\\", "/")
        if not s or s.startswith("/") or ":" in s or ".." in s.split("/"):
            out.append(f"{e.id}: postInstall {op} wants a path relative to mods/<name>/ "
                       f"that stays inside it, got {rel!r}")
    return out
