<#
.SYNOPSIS
    Prove which end of MO2's modlist.txt wins a file conflict.

.DESCRIPTION
    The most dangerous untested assumption in this project. `modlist.txt` is written
    bottom-up: the LAST line is the lowest-priority mod and the FIRST line wins conflicts.
    Get it backwards and you produce an instance that installs cleanly, launches fine, and
    silently resolves every conflict the wrong way — a build that dies hours later with no
    clue why, which is the exact failure this project exists to prevent.

    It cannot be checked by reading. So: two synthetic mods that ship the SAME file with
    different contents, installed both ways round, with the winner read back from inside
    MO2's virtual filesystem.

    Synthetic mods are better than real ones here. The conflict is unambiguous, the payload
    is one byte of signal, and the test needs no downloads, no Nexus, and no game launch.

.NOTES
    Needs no headset and never starts the game — the probe is a PowerShell process run
    inside usvfs, so this is CI-safe and takes seconds.
#>
[CmdletBinding()]
param(
    [string]$Instance = 'C:\Modding\mo2_fo4vr',
    [string]$Profile  = 'Default'
)

$ErrorActionPreference = 'Stop'

$mo2      = Join-Path $Instance 'ModOrganizer.exe'
$profDir  = Join-Path $Instance "profiles\$Profile"
$modlist  = Join-Path $profDir  'modlist.txt'
$modsDir  = Join-Path $Instance 'mods'
$probePs1 = Join-Path $Instance 'vfsprobe.ps1'
$probeOut = Join-Path $Instance 'vfsprobe-result.txt'

# Data-relative path both synthetic mods claim. Scripts/ is a real game Data subdir, so
# this exercises the same code path a genuine conflict would.
$conflictRel = 'Scripts\modlist-agent-conflict-probe.txt'

if (-not (Test-Path $mo2)) { throw "no MO2 at $mo2" }

$modA = 'zz-conflict-probe-A'
$modB = 'zz-conflict-probe-B'

Write-Output '== building two synthetic mods that claim the same file =='
foreach ($m in @(@{n=$modA;v='AAA'}, @{n=$modB;v='BBB'})) {
    $dir = Join-Path $modsDir "$($m.n)\Scripts"
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
    Set-Content -Path (Join-Path $modsDir "$($m.n)\$conflictRel") -Value $m.v -Encoding ascii -NoNewline
    Set-Content -Path (Join-Path $modsDir "$($m.n)\meta.ini") -Encoding ascii -Value @"
[General]
gameName=Fallout4VR
modid=0
version=1.0.0.0
notes="Synthetic test fixture written by core/tests/test-conflict-order.ps1. Safe to delete."
"@
}

# The probe runs INSIDE usvfs and reads the virtualised Data dir, so it observes exactly
# what the game engine would.
Set-Content -Path $probePs1 -Encoding ascii -Value @"
`$ErrorActionPreference = 'SilentlyContinue'
`$target = 'C:\Program Files (x86)\Steam\steamapps\common\Fallout 4 VR\Data\$conflictRel'
`$v = Get-Content -Raw -Path `$target
Set-Content -Path '$probeOut' -Value `$v -Encoding ascii -NoNewline
"@

function Invoke-Probe([string[]]$OrderTopFirst) {
    # modlist.txt as MO2 writes it. We pass the order exactly as it should appear in the
    # file; interpreting it is the whole point of the test, so the test itself must not
    # apply any reversal.
    $lines = @('# This file was automatically generated by Mod Organizer.')
    $lines += $OrderTopFirst | ForEach-Object { "+$_" }
    Set-Content -Path $modlist -Value $lines -Encoding ascii

    Remove-Item $probeOut -ErrorAction SilentlyContinue
    Get-Process ModOrganizer -ErrorAction SilentlyContinue | Stop-Process -Force
    Start-Sleep -Seconds 2

    Start-Process -FilePath $mo2 -WorkingDirectory $Instance `
        -ArgumentList '-p', $Profile, 'moshortcut://:VfsProbe' | Out-Null

    $deadline = (Get-Date).AddSeconds(60)
    while ((Get-Date) -lt $deadline -and -not (Test-Path $probeOut)) { Start-Sleep -Milliseconds 500 }

    Get-Process ModOrganizer -ErrorAction SilentlyContinue | Stop-Process -Force
    if (-not (Test-Path $probeOut)) { return $null }   # inconclusive, NOT a pass
    (Get-Content -Raw $probeOut).Trim()
}

Write-Output "== run 1: $modA listed FIRST =="
$r1 = Invoke-Probe @($modA, $modB)
Write-Output "   virtual Data contained: $(if ($null -eq $r1) {'<no result - probe did not run>'} else {$r1})"

Write-Output "== run 2: $modB listed FIRST =="
$r2 = Invoke-Probe @($modB, $modA)
Write-Output "   virtual Data contained: $(if ($null -eq $r2) {'<no result - probe did not run>'} else {$r2})"

Write-Output ''
if ($null -eq $r1 -or $null -eq $r2) {
    Write-Output 'RESULT: INCONCLUSIVE - the probe produced no output.'
    Write-Output '        Not a failure and not a pass. Check the VfsProbe executable exists'
    Write-Output '        in ModOrganizer.ini and that MO2 starts without a dialog.'
    exit 2
}
if ($r1 -eq $r2) {
    Write-Output "RESULT: FAIL - order made no difference (both runs saw '$r1')."
    Write-Output '        Either virtualisation is not working or the mods are not both enabled.'
    exit 1
}
if ($r1 -eq 'AAA' -and $r2 -eq 'BBB') {
    Write-Output 'RESULT: PASS - the FIRST line of modlist.txt WINS.'
    Write-Output '        So order.install in the manifest (winner first) maps DIRECTLY to'
    Write-Output '        modlist.txt with NO reversal. docs/MO2_PORTABLE.md must be corrected.'
    exit 0
}
if ($r1 -eq 'BBB' -and $r2 -eq 'AAA') {
    Write-Output 'RESULT: PASS - the LAST line of modlist.txt WINS.'
    Write-Output '        So the writer MUST reverse manifest order.install (winner first)'
    Write-Output '        when emitting modlist.txt. This is the documented assumption.'
    exit 0
}
Write-Output "RESULT: UNEXPECTED - r1='$r1' r2='$r2'"
exit 1
